### ISSUE TITLE
Error Argument #2 ($array) must be of type array

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/notify#18]
After some testing, installing and uninstalling this module in a testing site, I ended up with this error:

```
TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given a notify_admin_defaults() (línia 671 de /www/modules/notify/notify.admin.inc).
```
when accessing t/admin/config/people/notify/defaults

I found the problem and will send a pr

**Comment by robertgarrigos** [comment]
mmm I just realize that I was using latest release code, which is not the latest code, where this problem doesn't exist.

**Comment by robertgarrigos** [comment]
In fact, yes, it still there, just in a different place. Will issue a pr.

**Comment by huizache** [comment]
I find the same problem @robertgarrigos, but do not understand if you have fixed it, and if so where is the new code that fixes it...
I am using Notify 1.x-1.3.1

**Comment by argiepiano** [comment]
This fix has not been merged yet. You can see it here:
https://github.com/backdrop-contrib/notify/pull/19

**Comment by argiepiano** [comment]
I just merged this into the dev version of the module, on behalf of the @backdrop-contrib/bug-squad. The fix was correct, and was submitted 2 years ago.

You should try the dev version with this fix. Eventually there will be a new release of the module.
